name: Checking AS01 Build 

on:
  push:
    branches:
      - main

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Check number of branches
      run: |
        git fetch --all
        git branch -r | grep -v main | wc -l
        # Check for non-main branches

    - name: Check commit history
      run: |
        git log --oneline | wc -l
        # Check number of commits
    
    # Check CI/CD validation
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate CI workflow file
      run: |
        if [ -f ".github/workflows/ci.yml" ]; then
          echo "CI pipeline file found."
        else
          echo "CI pipeline file is missing."
          exit 1
        fi

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # App running    
    - name: Build Docker image
      run: |
        docker build -t musicfinder .
        docker run -d -p 8080:8080 musicfinder &
        sleep 10

    - name: Check if app is running on port 8080
      run: |
        curl --fail http://localhost:8080 || exit 1
